[package]
name = "compiler"
version = "0.1.0"
edition = "2018"

[dependencies]
lazy_static = "1.4.0"
lalrpop-util = "0.22.0"
koopa = "0.0.8"
rand = "0.9.0-beta.1"

[build-dependencies]
lalrpop = "0.22.0"
